doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            PatientManagement:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ibs/Context/PatientManagement/Entity'
                prefix: 'Ibs\Context\PatientManagement\Entity'
                alias: PatientManagement
            TreatmentTherapy:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ibs/Context/TreatmentTherapy/Entity'
                prefix: 'Ibs\Context\TreatmentTherapy\Entity'
                alias: TreatmentTherapy
            AICDSS:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ibs/Context/AICDSS/Entity'
                prefix: 'Ibs\Context\AICDSS\Entity'
                alias: AICDSS
            LabIoTGateway:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ibs/Context/LabIoTGateway/Entity'
                prefix: 'Ibs\Context\LabIoTGateway\Entity'
                alias: LabIoTGateway
            AdaptivePlanning:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ibs/Context/AdaptivePlanning/Entity'
                prefix: 'Ibs\Context\AdaptivePlanning\Entity'
                alias: AdaptivePlanning
            Communication:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ibs/Context/Communication/Entity'
                prefix: 'Ibs\Context\Communication\Entity'
                alias: Communication
            SecurityIdentity:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ibs/Context/SecurityIdentity/Entity'
                prefix: 'Ibs\Context\SecurityIdentity\Entity'
                alias: SecurityIdentity
            SharedCommon:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ibs/Shared/Common/Entity'
                prefix: 'Ibs\Shared\Common\Entity'
                alias: SharedCommon
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@dev:
    doctrine:
        dbal:
            logging: true
            profiling: true
        orm:
            auto_generate_proxy_classes: true
