<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260901211454 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Russian comments (COMMENT ON TABLE/COLUMN) for all domain tables and columns';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("COMMENT ON TABLE patients IS 'Пациенты'");
        $this->addSql("COMMENT ON TABLE hospitals IS 'Больницы'");
        $this->addSql("COMMENT ON TABLE patient_phones IS 'Телефоны пациентов'");
        $this->addSql("COMMENT ON TABLE phone_types IS 'Типы телефонов'");
        $this->addSql("COMMENT ON TABLE treatments IS 'Лечения'");
        $this->addSql("COMMENT ON TABLE drugs IS 'Препараты'");
        $this->addSql("COMMENT ON TABLE drug_groups IS 'Группы препаратов'");
        $this->addSql("COMMENT ON TABLE mkb10 IS 'Коды МКБ-10'");
        $this->addSql("COMMENT ON TABLE appointments IS 'Назначения'");
        $this->addSql("COMMENT ON TABLE test_history IS 'Анализы (история МНО)'");
        $this->addSql("COMMENT ON TABLE test_histories_by_assistant IS 'Анализы (данные ассистента)'");
        $this->addSql("COMMENT ON TABLE patient_requests IS 'Обращения пациентов'");
        $this->addSql("COMMENT ON TABLE treatment_notes IS 'Заметки лечения'");
        $this->addSql("COMMENT ON TABLE treatment_code_generator IS 'Генератор кода лечения'");
        $this->addSql("COMMENT ON TABLE users IS 'Пользователи'");
        $this->addSql("COMMENT ON TABLE medical_personnel IS 'Медицинский персонал'");
        $this->addSql("COMMENT ON TABLE med_personnel_phones IS 'Телефоны медперсонала'");
        $this->addSql("COMMENT ON TABLE users_for_hospitals IS 'Пользователи больниц'");
        $this->addSql("COMMENT ON TABLE sms_in IS 'Входящие SMS'");
        $this->addSql("COMMENT ON TABLE sms_out IS 'Исходящие SMS'");
        $this->addSql("COMMENT ON TABLE sms_out_packets IS 'Пакеты исходящих SMS'");
        $this->addSql("COMMENT ON TABLE sms_out_statuses IS 'Статусы исходящих SMS'");
        $this->addSql("COMMENT ON TABLE sms_templates IS 'Шаблоны SMS'");
        $this->addSql("COMMENT ON TABLE notification_logs IS 'Логи уведомлений'");
        $this->addSql("COMMENT ON TABLE notification_templates IS 'Шаблоны уведомлений'");
        $this->addSql("COMMENT ON TABLE patient_channel_identities IS 'Контакты каналов связи пациентов'");
        $this->addSql("COMMENT ON TABLE max_deeplinks IS 'Диплинки MAX'");
        $this->addSql("COMMENT ON TABLE genetic_markers IS 'Генетические маркеры'");
        $this->addSql("COMMENT ON TABLE genetic_marker_values IS 'Значения генетических маркеров'");
        $this->addSql("COMMENT ON TABLE marker_drug_relations IS 'Связи маркеров и препаратов'");
        $this->addSql("COMMENT ON TABLE patient_genetic_results IS 'Результаты фармакогенетики'");
        $this->addSql("COMMENT ON TABLE patient_vitals IS 'Витальные показатели'");
        $this->addSql("COMMENT ON TABLE patient_vitals_latest IS 'Последние витальные показатели'");
        $this->addSql("COMMENT ON TABLE test_plans IS 'Планы анализов'");
        $this->addSql("COMMENT ON TABLE hospital_test_plans IS 'Планы анализов по больницам'");
        $this->addSql("COMMENT ON TABLE holidays IS 'Праздничные и выходные дни'");
        $this->addSql("COMMENT ON TABLE supervisors IS 'Кураторы'");
        $this->addSql('COMMENT ON COLUMN appointments.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN appointments.treatment_id IS \'Лечение\'');
        $this->addSql('COMMENT ON COLUMN appointments.sms_id IS \'SMS\'');
        $this->addSql('COMMENT ON COLUMN appointments.drug_id IS \'Препарат\'');
        $this->addSql('COMMENT ON COLUMN appointments.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN appointments.appointment_dt IS \'Дата назначения\'');
        $this->addSql('COMMENT ON COLUMN appointments.creation_dt IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN appointments.doze IS \'Доза\'');
        $this->addSql('COMMENT ON COLUMN appointments.doctor_name IS \'ФИО врача\'');
        $this->addSql('COMMENT ON COLUMN appointments.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN appointments.doze2 IS \'Вторая доза (чередование)\'');
        $this->addSql('COMMENT ON COLUMN drug_groups.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN drug_groups.name IS \'Название\'');
        $this->addSql('COMMENT ON COLUMN drug_groups.full_name IS \'Полное название\'');
        $this->addSql('COMMENT ON COLUMN drugs.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN drugs.group_id IS \'Группа препаратов\'');
        $this->addSql('COMMENT ON COLUMN drugs.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN drugs.nominative IS \'Название (именительный падеж)\'');
        $this->addSql('COMMENT ON COLUMN drugs.genitive IS \'Название (родительный падеж)\'');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.marker_id IS \'Генетический маркер\'');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.value IS \'Генотип\'');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.label IS \'Метка\'');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.description IS \'Описание\'');
        $this->addSql('COMMENT ON COLUMN genetic_markers.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN genetic_markers.gene_symbol IS \'Обозначение маркера\'');
        $this->addSql('COMMENT ON COLUMN genetic_markers.full_name IS \'Полное название\'');
        $this->addSql('COMMENT ON COLUMN genetic_markers.rs_id IS \'rs-идентификатор (SNP)\'');
        $this->addSql('COMMENT ON COLUMN genetic_markers.description IS \'Описание\'');
        $this->addSql('COMMENT ON COLUMN holidays.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN holidays.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN holidays.h_month IS \'Месяц\'');
        $this->addSql('COMMENT ON COLUMN holidays.h_day IS \'День\'');
        $this->addSql('COMMENT ON COLUMN holidays.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN holidays.h_year IS \'Год\'');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.hospital_id IS \'Больница (ЛПУ)\'');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.creation_dt IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.test_dt IS \'Дата явки (замера)\'');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.status IS \'Статус\'');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN hospitals.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN hospitals.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN hospitals.name IS \'Название\'');
        $this->addSql('COMMENT ON COLUMN hospitals.region IS \'Регион\'');
        $this->addSql('COMMENT ON COLUMN hospitals.sms_phone IS \'Телефон для SMS\'');
        $this->addSql('COMMENT ON COLUMN hospitals.address IS \'Адрес\'');
        $this->addSql('COMMENT ON COLUMN hospitals.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN marker_drug_relations.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN marker_drug_relations.marker_id IS \'Генетический маркер\'');
        $this->addSql('COMMENT ON COLUMN marker_drug_relations.drug_id IS \'Препарат\'');
        $this->addSql('COMMENT ON COLUMN max_deeplinks.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN max_deeplinks.patient_id IS \'ID пациента\'');
        $this->addSql('COMMENT ON COLUMN max_deeplinks.token IS \'Токен\'');
        $this->addSql('COMMENT ON COLUMN max_deeplinks.created_at IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.phone_type_id IS \'Тип телефона\'');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.person_id IS \'Медицинский персонал\'');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.number IS \'Номер телефона\'');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN medical_personnel.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN medical_personnel.hospital_id IS \'Больница\'');
        $this->addSql('COMMENT ON COLUMN medical_personnel.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN medical_personnel.name IS \'ФИО\'');
        $this->addSql('COMMENT ON COLUMN medical_personnel.post IS \'Должность\'');
        $this->addSql('COMMENT ON COLUMN medical_personnel.address IS \'Адрес\'');
        $this->addSql('COMMENT ON COLUMN medical_personnel.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN mkb10.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN mkb10.rec_code IS \'Код записи\'');
        $this->addSql('COMMENT ON COLUMN mkb10.mkb_code IS \'Код МКБ-10\'');
        $this->addSql('COMMENT ON COLUMN mkb10.mkb_name IS \'Название МКБ-10\'');
        $this->addSql('COMMENT ON COLUMN mkb10.id_parent IS \'Родительская запись\'');
        $this->addSql('COMMENT ON COLUMN mkb10.addl_code IS \'Дополнительный код\'');
        $this->addSql('COMMENT ON COLUMN mkb10.actual IS \'Актуальность\'');
        $this->addSql('COMMENT ON COLUMN mkb10.date IS \'Дата\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.patient_id IS \'ID пациента\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.treatment_id IS \'ID лечения\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.channel_type IS \'Канал связи\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.recipient_address IS \'Адрес получателя\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.priority IS \'Приоритет\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.template_code IS \'Код шаблона\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.status IS \'Статус\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.error_message IS \'Текст ошибки\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.created_at IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN notification_logs.external_id IS \'Внешний ID\'');
        $this->addSql('COMMENT ON COLUMN notification_templates.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN notification_templates.code IS \'Код\'');
        $this->addSql('COMMENT ON COLUMN notification_templates.channel IS \'Канал\'');
        $this->addSql('COMMENT ON COLUMN notification_templates.subject_template IS \'Тема\'');
        $this->addSql('COMMENT ON COLUMN notification_templates.body_template IS \'Тело\'');
        $this->addSql('COMMENT ON COLUMN notification_templates.description IS \'Описание\'');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.patient_id IS \'ID пациента\'');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.channel_type IS \'Тип канала\'');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.value IS \'Значение\'');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.created_at IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.updated_at IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.patient_id IS \'Пациент\'');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.marker_id IS \'Генетический маркер\'');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.marker_value_id IS \'Значение маркера\'');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.created_at IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.updated_at IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.created_by IS \'Кем создано\'');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.updated_by IS \'Кем изменено\'');
        $this->addSql('COMMENT ON COLUMN patient_phones.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN patient_phones.phone_type_id IS \'Тип телефона\'');
        $this->addSql('COMMENT ON COLUMN patient_phones.person_id IS \'Пациент\'');
        $this->addSql('COMMENT ON COLUMN patient_phones.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN patient_phones.number IS \'Номер телефона\'');
        $this->addSql('COMMENT ON COLUMN patient_phones.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN patient_requests.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN patient_requests.treatment_id IS \'Лечение\'');
        $this->addSql('COMMENT ON COLUMN patient_requests.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN patient_requests.creation_dt IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN patient_requests.reason IS \'Причина\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.patient_id IS \'Пациент\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.treatment_id IS \'Лечение\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.record_dt IS \'Дата и время записи\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.hb IS \'Гемоглобин\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.heart_rate IS \'Пульс\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.systolic_pressure IS \'Систолическое давление\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.diastolic_pressure IS \'Диастолическое давление\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.saturation IS \'Сатурация\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.created_at IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.updated_at IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.created_by IS \'Кем создано\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.updated_by IS \'Кем изменено\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals.weight IS \'Вес\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.patient_id IS \'Пациент\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.hb IS \'Гемоглобин\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.heart_rate IS \'Пульс\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.systolic_pressure IS \'Систолическое давление\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.diastolic_pressure IS \'Диастолическое давление\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.saturation IS \'Сатурация\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.weight IS \'Вес\'');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.last_updated IS \'Дата последнего обновления\'');
        $this->addSql('COMMENT ON COLUMN patients.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN patients.hospital_id IS \'Больница\'');
        $this->addSql('COMMENT ON COLUMN patients.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN patients.firstname IS \'Имя\'');
        $this->addSql('COMMENT ON COLUMN patients.second_name IS \'Отчество\'');
        $this->addSql('COMMENT ON COLUMN patients.lastname IS \'Фамилия\'');
        $this->addSql('COMMENT ON COLUMN patients.birthday IS \'Дата рождения\'');
        $this->addSql('COMMENT ON COLUMN patients.sex IS \'Пол\'');
        $this->addSql('COMMENT ON COLUMN patients.sms_phone IS \'Телефон для SMS\'');
        $this->addSql('COMMENT ON COLUMN patients.address IS \'Адрес\'');
        $this->addSql('COMMENT ON COLUMN patients.passport IS \'Паспорт\'');
        $this->addSql('COMMENT ON COLUMN patients.health_insurance IS \'Полис ОМС\'');
        $this->addSql('COMMENT ON COLUMN patients.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN patients.snils IS \'СНИЛС\'');
        $this->addSql('COMMENT ON COLUMN patients.email IS \'Email\'');
        $this->addSql('COMMENT ON COLUMN phone_types.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN phone_types.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN phone_types.name IS \'Название\'');
        $this->addSql('COMMENT ON COLUMN phone_types.mask IS \'Маска\'');
        $this->addSql('COMMENT ON COLUMN phone_types.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN sms_in.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN sms_in.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN sms_in.treatment_id IS \'ID лечения\'');
        $this->addSql('COMMENT ON COLUMN sms_in.server_id IS \'ID сервера\'');
        $this->addSql('COMMENT ON COLUMN sms_in.sms_source IS \'Источник SMS\'');
        $this->addSql('COMMENT ON COLUMN sms_in.num IS \'Номер\'');
        $this->addSql('COMMENT ON COLUMN sms_in.text IS \'Текст\'');
        $this->addSql('COMMENT ON COLUMN sms_in.creation_dt IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN sms_in.status IS \'Статус\'');
        $this->addSql('COMMENT ON COLUMN sms_in.dt IS \'Дата\'');
        $this->addSql('COMMENT ON COLUMN sms_out.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN sms_out.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN sms_out.treatment_id IS \'ID лечения\'');
        $this->addSql('COMMENT ON COLUMN sms_out.sms_source IS \'Источник SMS\'');
        $this->addSql('COMMENT ON COLUMN sms_out.sms_target IS \'Целевой номер\'');
        $this->addSql('COMMENT ON COLUMN sms_out.creation_dt IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN sms_out.text IS \'Текст\'');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.server_packet_id IS \'ID пакета на сервере\'');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.balance IS \'Баланс\'');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.server_code IS \'Код сервера\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.sms_id IS \'ID SMS\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.server_code IS \'Код сервера\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.packet_id IS \'ID пакета\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.server_id IS \'ID сервера\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.phone_zone IS \'Телефонная зона\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.parts IS \'Части\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.credits IS \'Кредиты\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.status IS \'Статус\'');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.error IS \'Ошибка\'');
        $this->addSql('COMMENT ON COLUMN sms_templates.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN sms_templates.sms_type IS \'Тип SMS\'');
        $this->addSql('COMMENT ON COLUMN sms_templates.sms_source IS \'Источник SMS\'');
        $this->addSql('COMMENT ON COLUMN sms_templates.sms_template IS \'Шаблон SMS\'');
        $this->addSql('COMMENT ON COLUMN sms_templates.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN supervisors.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN supervisors.user_id IS \'Куратор (пользователь)\'');
        $this->addSql('COMMENT ON COLUMN supervisors.plan_id IS \'План анализов больницы\'');
        $this->addSql('COMMENT ON COLUMN supervisors.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.test_history_id IS \'Анализ (история МНО)\'');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.assistant_id IS \'Ассистент (медперсонал)\'');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.user_id IS \'Пользователь\'');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.creation_dt IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN test_history.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN test_history.treatment_id IS \'Лечение\'');
        $this->addSql('COMMENT ON COLUMN test_history.drug_id IS \'Препарат\'');
        $this->addSql('COMMENT ON COLUMN test_history.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN test_history.sms_id IS \'ID SMS\'');
        $this->addSql('COMMENT ON COLUMN test_history.creation_dt IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN test_history.mno IS \'МНО\'');
        $this->addSql('COMMENT ON COLUMN test_history.doze IS \'Доза\'');
        $this->addSql('COMMENT ON COLUMN test_history.doze2 IS \'Вторая доза (чередование)\'');
        $this->addSql('COMMENT ON COLUMN test_history.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN test_plans.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN test_plans.treatment_id IS \'Лечение\'');
        $this->addSql('COMMENT ON COLUMN test_plans.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN test_plans.creation_dt IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN test_plans.test_dt IS \'Дата явки (замера)\'');
        $this->addSql('COMMENT ON COLUMN test_plans.status IS \'Статус\'');
        $this->addSql('COMMENT ON COLUMN test_plans.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN treatment_code_generator.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN treatment_code_generator.code IS \'Код\'');
        $this->addSql('COMMENT ON COLUMN treatment_code_generator.generate IS \'Генерация\'');
        $this->addSql('COMMENT ON COLUMN treatment_notes.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN treatment_notes.treatment_id IS \'Лечение\'');
        $this->addSql('COMMENT ON COLUMN treatment_notes.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN treatment_notes.creation_dt IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN treatment_notes.note IS \'Заметка\'');
        $this->addSql('COMMENT ON COLUMN treatments.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN treatments.patient_id IS \'Пациент\'');
        $this->addSql('COMMENT ON COLUMN treatments.drug_id IS \'Препарат\'');
        $this->addSql('COMMENT ON COLUMN treatments.mkb10_id IS \'Код МКБ-10\'');
        $this->addSql('COMMENT ON COLUMN treatments.mod_dt IS \'Дата изменения\'');
        $this->addSql('COMMENT ON COLUMN treatments.code IS \'Код лечения\'');
        $this->addSql('COMMENT ON COLUMN treatments.diagnosis IS \'Диагноз\'');
        $this->addSql('COMMENT ON COLUMN treatments.comorbidities IS \'Сопутствующие заболевания\'');
        $this->addSql('COMMENT ON COLUMN treatments.mno_from IS \'Целевой диапазон МНО (от)\'');
        $this->addSql('COMMENT ON COLUMN treatments.mno_to IS \'Целевой диапазон МНО (до)\'');
        $this->addSql('COMMENT ON COLUMN treatments.beg_dt IS \'Дата начала лечения\'');
        $this->addSql('COMMENT ON COLUMN treatments.plan_end_dt IS \'Плановая дата окончания\'');
        $this->addSql('COMMENT ON COLUMN treatments.real_end_dt IS \'Фактическая дата окончания\'');
        $this->addSql('COMMENT ON COLUMN treatments.stopping_reason IS \'Причина остановки\'');
        $this->addSql('COMMENT ON COLUMN treatments.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN treatments.hemorrhages IS \'Кровотечения\'');
        $this->addSql('COMMENT ON COLUMN treatments.flags IS \'Флаги\'');
        $this->addSql('COMMENT ON COLUMN treatments.diagnosis_code IS \'Код диагноза\'');
        $this->addSql('COMMENT ON COLUMN treatments.pin IS \'PIN-код\'');
        $this->addSql('COMMENT ON COLUMN users.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN users.medical_personnel_id IS \'Медицинский персонал\'');
        $this->addSql('COMMENT ON COLUMN users.login IS \'Логин\'');
        $this->addSql('COMMENT ON COLUMN users.password IS \'Пароль\'');
        $this->addSql('COMMENT ON COLUMN users.user_name IS \'Имя пользователя\'');
        $this->addSql('COMMENT ON COLUMN users.roles IS \'Роли\'');
        $this->addSql('COMMENT ON COLUMN users.comment IS \'Комментарий\'');
        $this->addSql('COMMENT ON COLUMN users_for_hospitals.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN users_for_hospitals.user_id IS \'Пользователь\'');
        $this->addSql('COMMENT ON COLUMN users_for_hospitals.hospital_id IS \'Больница\'');
        $this->addSql('COMMENT ON COLUMN users_for_hospitals.permissions IS \'Права доступа\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('COMMENT ON TABLE patients IS NULL');
        $this->addSql('COMMENT ON TABLE hospitals IS NULL');
        $this->addSql('COMMENT ON TABLE patient_phones IS NULL');
        $this->addSql('COMMENT ON TABLE phone_types IS NULL');
        $this->addSql('COMMENT ON TABLE treatments IS NULL');
        $this->addSql('COMMENT ON TABLE drugs IS NULL');
        $this->addSql('COMMENT ON TABLE drug_groups IS NULL');
        $this->addSql('COMMENT ON TABLE mkb10 IS NULL');
        $this->addSql('COMMENT ON TABLE appointments IS NULL');
        $this->addSql('COMMENT ON TABLE test_history IS NULL');
        $this->addSql('COMMENT ON TABLE test_histories_by_assistant IS NULL');
        $this->addSql('COMMENT ON TABLE patient_requests IS NULL');
        $this->addSql('COMMENT ON TABLE treatment_notes IS NULL');
        $this->addSql('COMMENT ON TABLE treatment_code_generator IS NULL');
        $this->addSql('COMMENT ON TABLE users IS NULL');
        $this->addSql('COMMENT ON TABLE medical_personnel IS NULL');
        $this->addSql('COMMENT ON TABLE med_personnel_phones IS NULL');
        $this->addSql('COMMENT ON TABLE users_for_hospitals IS NULL');
        $this->addSql('COMMENT ON TABLE sms_in IS NULL');
        $this->addSql('COMMENT ON TABLE sms_out IS NULL');
        $this->addSql('COMMENT ON TABLE sms_out_packets IS NULL');
        $this->addSql('COMMENT ON TABLE sms_out_statuses IS NULL');
        $this->addSql('COMMENT ON TABLE sms_templates IS NULL');
        $this->addSql('COMMENT ON TABLE notification_logs IS NULL');
        $this->addSql('COMMENT ON TABLE notification_templates IS NULL');
        $this->addSql('COMMENT ON TABLE patient_channel_identities IS NULL');
        $this->addSql('COMMENT ON TABLE max_deeplinks IS NULL');
        $this->addSql('COMMENT ON TABLE genetic_markers IS NULL');
        $this->addSql('COMMENT ON TABLE genetic_marker_values IS NULL');
        $this->addSql('COMMENT ON TABLE marker_drug_relations IS NULL');
        $this->addSql('COMMENT ON TABLE patient_genetic_results IS NULL');
        $this->addSql('COMMENT ON TABLE patient_vitals IS NULL');
        $this->addSql('COMMENT ON TABLE patient_vitals_latest IS NULL');
        $this->addSql('COMMENT ON TABLE test_plans IS NULL');
        $this->addSql('COMMENT ON TABLE hospital_test_plans IS NULL');
        $this->addSql('COMMENT ON TABLE holidays IS NULL');
        $this->addSql('COMMENT ON TABLE supervisors IS NULL');
        $this->addSql('COMMENT ON COLUMN holidays.id IS NULL');
        $this->addSql('COMMENT ON COLUMN holidays.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN holidays.h_month IS NULL');
        $this->addSql('COMMENT ON COLUMN holidays.h_day IS NULL');
        $this->addSql('COMMENT ON COLUMN holidays.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN holidays.h_year IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.treatment_id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.server_id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.sms_source IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.num IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.text IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.creation_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.status IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_in.dt IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.server_packet_id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.balance IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_packets.server_code IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_templates.id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_templates.sms_type IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_templates.sms_source IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_templates.sms_template IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_templates.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN treatment_code_generator.id IS NULL');
        $this->addSql('COMMENT ON COLUMN treatment_code_generator.code IS NULL');
        $this->addSql('COMMENT ON COLUMN treatment_code_generator.generate IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.id IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.patient_id IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.drug_id IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.mkb10_id IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.code IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.diagnosis IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.comorbidities IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.mno_from IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.mno_to IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.beg_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.plan_end_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.real_end_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.stopping_reason IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.hemorrhages IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.flags IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.diagnosis_code IS NULL');
        $this->addSql('COMMENT ON COLUMN treatments.pin IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.id IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.treatment_id IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.sms_id IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.drug_id IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.appointment_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.creation_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.doze IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.doctor_name IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN appointments.doze2 IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out.id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out.treatment_id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out.sms_source IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out.sms_target IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out.creation_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out.text IS NULL');
        $this->addSql('COMMENT ON COLUMN drugs.id IS NULL');
        $this->addSql('COMMENT ON COLUMN drugs.group_id IS NULL');
        $this->addSql('COMMENT ON COLUMN drugs.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN drugs.nominative IS NULL');
        $this->addSql('COMMENT ON COLUMN drugs.genitive IS NULL');
        $this->addSql('COMMENT ON COLUMN drug_groups.id IS NULL');
        $this->addSql('COMMENT ON COLUMN drug_groups.name IS NULL');
        $this->addSql('COMMENT ON COLUMN drug_groups.full_name IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_markers.id IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_markers.gene_symbol IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_markers.full_name IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_markers.rs_id IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_markers.description IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.id IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.marker_id IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.value IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.label IS NULL');
        $this->addSql('COMMENT ON COLUMN genetic_marker_values.description IS NULL');
        $this->addSql('COMMENT ON COLUMN hospitals.id IS NULL');
        $this->addSql('COMMENT ON COLUMN hospitals.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN hospitals.name IS NULL');
        $this->addSql('COMMENT ON COLUMN hospitals.region IS NULL');
        $this->addSql('COMMENT ON COLUMN hospitals.sms_phone IS NULL');
        $this->addSql('COMMENT ON COLUMN hospitals.address IS NULL');
        $this->addSql('COMMENT ON COLUMN hospitals.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.id IS NULL');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.hospital_id IS NULL');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.creation_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.test_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.status IS NULL');
        $this->addSql('COMMENT ON COLUMN hospital_test_plans.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN marker_drug_relations.id IS NULL');
        $this->addSql('COMMENT ON COLUMN marker_drug_relations.marker_id IS NULL');
        $this->addSql('COMMENT ON COLUMN marker_drug_relations.drug_id IS NULL');
        $this->addSql('COMMENT ON COLUMN phone_types.id IS NULL');
        $this->addSql('COMMENT ON COLUMN phone_types.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN phone_types.name IS NULL');
        $this->addSql('COMMENT ON COLUMN phone_types.mask IS NULL');
        $this->addSql('COMMENT ON COLUMN phone_types.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.id IS NULL');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.phone_type_id IS NULL');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.person_id IS NULL');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.number IS NULL');
        $this->addSql('COMMENT ON COLUMN med_personnel_phones.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN medical_personnel.id IS NULL');
        $this->addSql('COMMENT ON COLUMN medical_personnel.hospital_id IS NULL');
        $this->addSql('COMMENT ON COLUMN medical_personnel.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN medical_personnel.name IS NULL');
        $this->addSql('COMMENT ON COLUMN medical_personnel.post IS NULL');
        $this->addSql('COMMENT ON COLUMN medical_personnel.address IS NULL');
        $this->addSql('COMMENT ON COLUMN medical_personnel.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.id IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.hospital_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.firstname IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.second_name IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.lastname IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.birthday IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.sex IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.sms_phone IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.address IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.passport IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.health_insurance IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.snils IS NULL');
        $this->addSql('COMMENT ON COLUMN patients.email IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.patient_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.marker_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.marker_value_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.created_by IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_genetic_results.updated_by IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_phones.id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_phones.phone_type_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_phones.person_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_phones.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_phones.number IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_phones.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_requests.id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_requests.treatment_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_requests.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_requests.creation_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_requests.reason IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.patient_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.treatment_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.record_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.hb IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.heart_rate IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.systolic_pressure IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.diastolic_pressure IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.saturation IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.created_by IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.updated_by IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals.weight IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.patient_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.hb IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.heart_rate IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.systolic_pressure IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.diastolic_pressure IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.saturation IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.weight IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_vitals_latest.last_updated IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.sms_id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.server_code IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.packet_id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.server_id IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.phone_zone IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.parts IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.credits IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.status IS NULL');
        $this->addSql('COMMENT ON COLUMN sms_out_statuses.error IS NULL');
        $this->addSql('COMMENT ON COLUMN users.id IS NULL');
        $this->addSql('COMMENT ON COLUMN users.medical_personnel_id IS NULL');
        $this->addSql('COMMENT ON COLUMN users.login IS NULL');
        $this->addSql('COMMENT ON COLUMN users.password IS NULL');
        $this->addSql('COMMENT ON COLUMN users.user_name IS NULL');
        $this->addSql('COMMENT ON COLUMN users.roles IS NULL');
        $this->addSql('COMMENT ON COLUMN users.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN supervisors.id IS NULL');
        $this->addSql('COMMENT ON COLUMN supervisors.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN supervisors.plan_id IS NULL');
        $this->addSql('COMMENT ON COLUMN supervisors.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.treatment_id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.drug_id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.sms_id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.creation_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.mno IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.doze IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.doze2 IS NULL');
        $this->addSql('COMMENT ON COLUMN test_history.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.test_history_id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.assistant_id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.creation_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN test_histories_by_assistant.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN test_plans.id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_plans.treatment_id IS NULL');
        $this->addSql('COMMENT ON COLUMN test_plans.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN test_plans.creation_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN test_plans.test_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN test_plans.status IS NULL');
        $this->addSql('COMMENT ON COLUMN test_plans.comment IS NULL');
        $this->addSql('COMMENT ON COLUMN treatment_notes.id IS NULL');
        $this->addSql('COMMENT ON COLUMN treatment_notes.treatment_id IS NULL');
        $this->addSql('COMMENT ON COLUMN treatment_notes.mod_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN treatment_notes.creation_dt IS NULL');
        $this->addSql('COMMENT ON COLUMN treatment_notes.note IS NULL');
        $this->addSql('COMMENT ON COLUMN mkb10.id IS NULL');
        $this->addSql('COMMENT ON COLUMN mkb10.rec_code IS NULL');
        $this->addSql('COMMENT ON COLUMN mkb10.mkb_code IS NULL');
        $this->addSql('COMMENT ON COLUMN mkb10.mkb_name IS NULL');
        $this->addSql('COMMENT ON COLUMN mkb10.id_parent IS NULL');
        $this->addSql('COMMENT ON COLUMN mkb10.addl_code IS NULL');
        $this->addSql('COMMENT ON COLUMN mkb10.actual IS NULL');
        $this->addSql('COMMENT ON COLUMN mkb10.date IS NULL');
        $this->addSql('COMMENT ON COLUMN users_for_hospitals.id IS NULL');
        $this->addSql('COMMENT ON COLUMN users_for_hospitals.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN users_for_hospitals.hospital_id IS NULL');
        $this->addSql('COMMENT ON COLUMN users_for_hospitals.permissions IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_templates.id IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_templates.code IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_templates.channel IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_templates.subject_template IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_templates.body_template IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_templates.description IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.patient_id IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.channel_type IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.value IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN patient_channel_identities.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.id IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.patient_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.treatment_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.channel_type IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.recipient_address IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.priority IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.template_code IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.status IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.external_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.error_message IS NULL');
        $this->addSql('COMMENT ON COLUMN notification_logs.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN max_deeplinks.id IS NULL');
        $this->addSql('COMMENT ON COLUMN max_deeplinks.patient_id IS NULL');
        $this->addSql('COMMENT ON COLUMN max_deeplinks.token IS NULL');
        $this->addSql('COMMENT ON COLUMN max_deeplinks.created_at IS NULL');
    }
}
